export const GET_POKEMON = 'POKEDEX.GET_POKEMON'

export const GET_POKEMON_SPECIES = 'POKEDEX.GET_POKEMON_SPECIES'

export const GET_POKEMON_EVOLUTION_CHAIN = 'POKEDEX.GET_POKEMON_EVOLUTION_CHAIN'

export const GET_POKEMON_LOCATIONS = 'POKEDEX.GET_POKEMON_LOCATIONS'
